logging:
  level:
    #root: debug
    com.garmin.gemfire.transfer: debug
  file: /var/log/kafka-consumers/loggerFile
server:
  port: 8081
spring:
  kafka:
    bootstrap-servers:
    - olaxda-itwgfkafka07:9092
    - olaxda-itwgfkafka08:9092
    - olaxda-itwgfkafka09:9092
  cloud:
    stream:
      kafka:
        binder:
          zkNodes:
          - olaxda-itwgfkafka07:2181
          - olaxda-itwgfkafka08:2181
          - olaxda-itwgfkafka09:2181          
      bindings:
        input:
          destination: sso_ticketGrantingTicket-dev-data
          consumer:
            header-mode: raw
          group: kafka-subscriber-3  